[debug]
default_type = "cpp"

[setup]
# 在运行测试之前需要执行的准备步骤

[[setup.steps]]
name = "Compile tsh"
type = "command"
command = "make"
args = ["all", "-j"]
required = true                               # 如果这一步失败，则终止所有测试
message = "Preparing tsh..."
success_message = "tsh compiled successfully"
timeout = 60.0

# 可以添加更多setup步骤
# [[setup.steps]]
# name = "其他准备步骤"
# type = "command"  # 可以是普通命令
# command = "./some_script.sh"
# args = ["arg1", "arg2"]
# required = false  # 这一步失败不会终止测试

[paths]
# 定义项目中重要路径的配置
tests_dir = "tests"
cases_dir = "tests/cases"
common_dir = "tests/common"

[grader]
# 评分器的全局配置
default_timeout = 5.0 # 默认超时时间（秒）

[executables]
# 预定义的可执行文件
tsh = "${root_dir}/tsh"
tshref = "${root_dir}/tshref"
