name: 改进建议
description: 为 Shell Lab 实验提出改进建议
title: "[建议] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你为 Shell Lab 实验提出改进建议！请详细描述你的想法，这将帮助我们不断完善实验内容。

  - type: dropdown
    id: task
    attributes:
      label: 相关任务
      description: 这个建议主要涉及哪个任务？
      options:
        - 基础功能：命令执行与进程管理
        - 基础功能：信号处理
        - 基础功能：作业控制
        - 基础功能：I/O 重定向
        - 选做任务：基本管道支持
        - 选做任务：高级管道支持
        - 选做任务：环境变量展开
        - 选做任务：命令替换功能
        - 选做任务：终端控制机制
        - 选做任务：PATH 环境变量支持
        - 选做任务：脚本执行功能
        - 选做任务：环境变量支持（export）
        - 选做任务：子 Shell（基础）
        - 选做任务：子 Shell（高级）
        - 整体框架/测试系统
        - 其他
      multiple: true
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 描述当前实验中存在的问题或不足
      placeholder: 例如：某个功能的实现方式不够清晰、测试用例覆盖不够全面等
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: 改进建议
      description: 详细描述你的改进建议
      placeholder: 请具体说明你的改进想法，可以包括代码示例、新的测试用例等
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: 预期效果
      description: 描述实施改进后会带来什么好处
      placeholder: 例如：更好地理解进程控制机制、提高代码质量、增加测试覆盖率等
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 实施建议
      description: 如果你有具体的实施方案，请在此说明
      placeholder: 可以包含具体的代码修改建议、新增功能的实现思路、测试用例设计等

  - type: textarea
    id: alternatives
    attributes:
      label: 其他方案
      description: 是否考虑过其他替代方案？为什么选择这个方案？
      placeholder: 请说明你考虑过的其他实现方案及其优缺点

  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      description: 在提交建议前，请确认以下内容
      options:
        - label: 我已经检查过现有的 issues，确认这不是一个重复的建议
          required: true
        - label: 这个建议是具体且可实施的
          required: true
